[project]
name = "mffpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.4"
dependencies = [
    "Deprecated>=1.2.12",
    "flake8==3.8.4",
    "lxml>=4.8.0",
    "mypy>=0.660",
    "numpy>=1.15.1",
    "pre-commit>=2.7.1",
    "pytest>=5.2.0",
    "pytest-cov>=2.6.1",
    "pytz>=2019.2",
    "types-deprecated>=0.1.1",
    "types-pytz>=0.1.0",
]
